
spring:
  datasource:
    password: zhuang1996
    username: zhuang
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.218.59:3306/mojito?serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull

  data:
    mongodb:
      host: 47.103.218.59
      port: 27017
      database: mojito
  #redis
  redis:
    database: 0
    host: 47.103.218.59
    port: 6379
    password: zhuang1996
    timeout: 500


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.codeeyes.mojito.model.entity
#  configuration:
# 开启驼峰uName自动映射到u_name
#map-underscore-to-camel-case: true

# 打印sql
logging:
  level:
    ssm.app.mapper : debug

springfox:
 documentation:
  swagger:
   v2:
#    host: localhost:80/api
     host: 47.103.218.59:81/api


server:
  #  端口号
#  port: 8080
#  服务器端口
  port: 8091
  servlet:
    context-path: /photoWall